"""initial schema

Revision ID: ce008abd70ae
Revises: 
Create Date: 2026-04-27 21:53:56.693701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce008abd70ae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_architectural_decisions_repo_id'), 'architectural_decisions', ['repo_id'], unique=False)
    # uq_chat_session_turno_role skipped — duplicatas existentes no banco; limpar antes de adicionar
    op.create_index('ix_dev_signals_projeto_tipo_ts', 'dev_signals', ['projeto', 'tipo', 'ts'], unique=False)
    op.create_index(op.f('ix_indexing_log_repo_id'), 'indexing_log', ['repo_id'], unique=False)
    op.alter_column('mcp_connections', 'pending_skills_update',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('idx_mcp_connections_last_seen', table_name='mcp_connections')
    op.create_index('ix_session_contexts_projeto_timestamp', 'session_contexts', ['projeto', 'timestamp'], unique=False)
    op.alter_column('ssh_identities', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_ssh_identities_lookup', table_name='ssh_identities')
    op.drop_constraint('ssh_identities_ssh_ip_ssh_port_key', 'ssh_identities', type_='unique')
    op.create_index(op.f('ix_ssh_identities_expires_at'), 'ssh_identities', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ssh_identities_expires_at'), table_name='ssh_identities')
    op.create_unique_constraint('ssh_identities_ssh_ip_ssh_port_key', 'ssh_identities', ['ssh_ip', 'ssh_port'])
    op.create_index('idx_ssh_identities_lookup', 'ssh_identities', ['ssh_ip', 'ssh_port', 'expires_at'], unique=False)
    op.alter_column('ssh_identities', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_session_contexts_projeto_timestamp', table_name='session_contexts')
    op.create_index('idx_mcp_connections_last_seen', 'mcp_connections', [sa.text('last_seen_at DESC')], unique=False)
    op.alter_column('mcp_connections', 'pending_skills_update',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_indexing_log_repo_id'), table_name='indexing_log')
    op.drop_index('ix_dev_signals_projeto_tipo_ts', table_name='dev_signals')
    # op.drop_constraint('uq_chat_session_turno_role', 'chat_messages', type_='unique')  # skipped no upgrade
    op.drop_index(op.f('ix_architectural_decisions_repo_id'), table_name='architectural_decisions')
    # ### end Alembic commands ###
